### ISSUE TITLE
3.12 support

### ISSUE THREAD

**Issue by Tinche** [MagicStack/immutables#104]
Howdy,

I know 3.12 isn't out yet. However, other projects (like my cattrs) might want to start testing early to catch regressions. And these projects might use immutables as a test dependency. Hence my plea ;)

**Comment by LecrisUT** [comment]
For reference, [here](https://kojipkgs.fedoraproject.org//work/tasks/995/103190995/build.log) are the build failures on Fedora

**Comment by elprans** [comment]
We'll take a look soon.  The issue is usually ABI stability and Cython support, so we normally wait for the first release candidate to start issuing builds for the next Python.

**Comment by Tinche** [comment]
Thanks!
