### ISSUE TITLE
pythoncapi_compat.h is 0BSD not MIT

### ISSUE THREAD

**Issue by mtelka** [MagicStack/immutables#108]
The [LICENSE](https://github.com/MagicStack/immutables/blob/master/LICENSE) file says the [pythoncapi_compat.h](https://github.com/MagicStack/immutables/blob/master/immutables/pythoncapi_compat.h) file is licensed under MIT, but actually the license of the file is 0BSD.

**Comment by elprans** [comment]
Might have been changed upstream at some point?  PR with the correction is up. Thanks for the heads up!
