### ISSUE TITLE
`immutables.Map.__str__` doesn't match `dict.__str__`

### ISSUE THREAD

**Issue by rowillia** [MagicStack/immutables#17]
```python
In [7]: d = {'a': 1}

In [8]: str(d)
Out[8]: "{'a': 1}"

In [9]: str(immutables.Map(d))
Out[9]: "<immutables.Map({'a': 1}) at 0x108ed56c0>"
```

**Comment by 1st1** [comment]
Yeah, I can fix this. What's the use case btw?

**Comment by rowillia** [comment]
I'm replacing some `dict` instances with `immutables.Map` and we're logging the dictionary in places using `__str__`.

**Comment by ofek** [comment]
This would help us as well for the same exact use case.
