### ISSUE TITLE
Some validations are always disabled

### ISSUE THREAD

**Issue by TIGirardi** [MagicStack/immutables#26]
These should probably be `#ifndef`. In particular, the first would catch #24 

https://github.com/MagicStack/immutables/blob/11863b29e3fbcd7d25335befce706e21a785f5e0/immutables/_map.c#L396-L415

https://github.com/MagicStack/immutables/blob/11863b29e3fbcd7d25335befce706e21a785f5e0/immutables/_map.c#L1112-L1120

https://github.com/MagicStack/immutables/blob/11863b29e3fbcd7d25335befce706e21a785f5e0/immutables/_map.c#L2009-L2018

https://github.com/MagicStack/immutables/blob/11863b29e3fbcd7d25335befce706e21a785f5e0/immutables/_map.c#L2301-L2304

https://github.com/MagicStack/immutables/blob/11863b29e3fbcd7d25335befce706e21a785f5e0/immutables/_map.c#L2338-L2341

https://github.com/MagicStack/immutables/blob/11863b29e3fbcd7d25335befce706e21a785f5e0/immutables/_map.c#L2362-L2365

https://github.com/MagicStack/immutables/blob/11863b29e3fbcd7d25335befce706e21a785f5e0/immutables/_map.c#L2384-L2387

**Comment by 1st1** [comment]
Yes, all of these are wrong and should be updated.

**Comment by 1st1** [comment]
> These should probably be #ifndef. In particular, the first would catch #24

The should be -- meaning that they shouldn't run in prod builds. I'm adding an environment variable to build debug builds and test them in CI, along with a new fuzz test.
