### ISSUE TITLE
Please add a changelog

### ISSUE THREAD

**Issue by jab** [MagicStack/immutables#30]
Looks like the new release might have some great improvements, but it’s harder to tell what they are without a changelog (or any description associated with the release on GitHub, for those of us watching releases).

Thanks for your work on Immutables!

**Comment by 1st1** [comment]
There's actually a single item worth mentioning in the changelog: https://github.com/MagicStack/immutables/releases/tag/v0.12

We've upgraded this repo to have the same release workflow as magicstack/uvloop etc. The next one will have a proper change log right away. Thanks!
