### ISSUE TITLE
Immutables Class

### ISSUE THREAD

**Issue by li-dennis** [MagicStack/immutables#47]
Maybe i'm missing something in the docs, but is there an immutables class that can be used/inherited from, or is this just a Map?

e.g. I'm hoping for an interface like this

```
class CustomClass(Immutables.Class):
  def __init__(self):
    self.x = 'x'

  def foo(self):
    self.x = 'y'
    pass

obj = CustomClass()
with obj.mutate() as obj:
  obj.foo()
  obj2 = obj.finish()

obj.x # returns x
obj2.x # returns y
```

**Comment by 1st1** [comment]
This isn't supported. Use composition, not inheritance.

**Comment by li-dennis** [comment]
Got it. I'll look into some other solutions then.

Rewriting to use composition isn't a great solution here since i'm inheriting an imperative and mutation heavy codebase.

Maybe gh issues isn't the appropriate place to be asking this question, but I'm looking for an incremental stepping stone to this refactor. Do you know of any sample projects that have done that with your library, or something similar?

**Comment by 1st1** [comment]
Yes, we did it for edgedb incrementally by first refactoring to code to look as if the underlying storable was immutable, and then flipping the switch to actually star using it. The refactoring took us a couple of weeks, I doubt you can follow it by reading the git history though.
