### ISSUE TITLE
Can't use Map class as generic on Python <=3.6

### ISSUE THREAD

**Issue by ariebovenberg** [MagicStack/immutables#49]
On python <=3.6 it isn't possible to use `Map` as a generic type:

```python
>>> from immutables import Map
>>> Map
<class 'immutables._map.Map'>
>>> Map[str, int]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

On python 3.7+, the problem does not occur. The likely reason is the use of `__class_getitem__`, which is [new in Python 3.7](https://www.python.org/dev/peps/pep-0560/).

Relevant code snippet below:

https://github.com/MagicStack/immutables/blob/82e540934b0297f081076783c2d11299d04425d8/immutables/_map.c#L3389-L3394

It looks like a metaclass will be needed to fix this. That, or inheriting directly from `typing.Mapping`. Not sure which is the preferred option.

**Comment by 1st1** [comment]
> The likely reason is the use of __class_getitem__, which is new in Python 3.7.

Yes. And there's nothing we can do here, sadly. `Map` is implemented in C, where `__class_getitem__` is the only way to make this work.

**Comment by ariebovenberg** [comment]
@1st1 thanks, I realize I forgot to check the _closed_ issues and I found you were already aware.

**Comment by 1st1** [comment]
np!
