### ISSUE TITLE
Data from benchmark and plot do not match

### ISSUE THREAD

**Issue by curusarn** [MagicStack/immutables#5]
Why is reguar dict faster than HAMT?

Plot does not seem to match with times that can be found alongside the banchmark code: https://gist.github.com/1st1/292e3f0bbe43bd65ff3256f80aa2637d

**Comment by 1st1** [comment]
How about you post your benchmark  results?

**Comment by curusarn** [comment]
My point is that your benchmark shows HAMT as the fastest but the plot in your readme shows regular dict as the fastest.

Data from benchmark and plot do not match.

Eg.:  
Data from your benchmark:
```
=============
  # of items: 1000; iterations: 1000000

  dict copy:			24.0334s
  hamt:				2.2156s
  PMap:				15.9785s
```
What I believe the plot tells me:
```
 # of items: 1000; iterations: 1000000
regular dict:     ~1s
HAMT:             ~1.8s
COW dict:       ~6.3s
```
The data either doesn't match or I didn't read your plot properly.
(The plot doesn't even go to 24 seconds as it should according to your benchmark.)

I don't see how doing another benchmark would help.

Sorry if I didn't word this clearly before.

Cheers.

**Comment by 1st1** [comment]
Yes, I think I referenced a wrong benchmark code, try this one: https://gist.github.com/1st1/9004813d5576c96529527d44c5457dcd

Regular dict is there just as a reference point as it's not immutable. COW is copy on write implemented with a regular dict (`dict.copy()` on every mutation).  So yes, HAMT is faster than COW, but would be slower than a regular dict if you don't need immutability.

**Comment by curusarn** [comment]
I was under impression that immutability should increase the speed of get-item calls.  
Now I get that the plot shows something different.

**Comment by 1st1** [comment]
> I was under impression that immutability should increase the speed of get-item calls.

No, immutability and speed of accessing a key are orthogonal things. The only thing that immutability gives you is the ability to copy the entire collection by reference.
