### ISSUE TITLE
Binary wheels for Python 3.9

### ISSUE THREAD

**Issue by ofek** [MagicStack/immutables#56]
Hello! Are there plans for a new release soon? cc @1st1 @vstinner

**Comment by vstinner** [comment]
> cc @1st1 @vstinner

I don't work on this project. I cannot help you.

**Comment by ofek** [comment]
Ah saw a commit, assumed you did :)

**Comment by 1st1** [comment]
We've just released v0.15 with wheels for 3.9.

**Comment by ofek** [comment]
Thank you!!!
