### ISSUE TITLE
Maintain Map insertion order like dict on Python 3.7+

### ISSUE THREAD

**Issue by ofek** [MagicStack/immutables#57]
Is that possible?

**Comment by hukkinj1** [comment]
I'd imagine [PEP603](https://www.python.org/dev/peps/pep-0603/) draft (essentially the spec) is relevant here:

> Iteration in frozenmap, unlike in dict, does not preserve the insertion order.

> ... Instead, frozenmap has an O(log N) cost of set/get operations

**Comment by 1st1** [comment]
Unfortunately this isn't possible without incurring increased memory usage and performance losses.
